/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginContinueRouteImport } from './routes/login/continue'
import { Route as PluginIdSplatRouteImport } from './routes/$pluginId.$'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginContinueRoute = LoginContinueRouteImport.update({
  id: '/login/continue',
  path: '/login/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginIdSplatRoute = PluginIdSplatRouteImport.update({
  id: '/$pluginId/$',
  path: '/$pluginId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/$pluginId/$': typeof PluginIdSplatRoute
  '/login/continue': typeof LoginContinueRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/$pluginId/$': typeof PluginIdSplatRoute
  '/login/continue': typeof LoginContinueRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/design-system': typeof DesignSystemRoute
  '/$pluginId/$': typeof PluginIdSplatRoute
  '/login/continue': typeof LoginContinueRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/design-system'
    | '/$pluginId/$'
    | '/login/continue'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/design-system'
    | '/$pluginId/$'
    | '/login/continue'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/design-system'
    | '/$pluginId/$'
    | '/login/continue'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DesignSystemRoute: typeof DesignSystemRoute
  PluginIdSplatRoute: typeof PluginIdSplatRoute
  LoginContinueRoute: typeof LoginContinueRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/continue': {
      id: '/login/continue'
      path: '/login/continue'
      fullPath: '/login/continue'
      preLoaderRoute: typeof LoginContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pluginId/$': {
      id: '/$pluginId/$'
      path: '/$pluginId/$'
      fullPath: '/$pluginId/$'
      preLoaderRoute: typeof PluginIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DesignSystemRoute: DesignSystemRoute,
  PluginIdSplatRoute: PluginIdSplatRoute,
  LoginContinueRoute: LoginContinueRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
